=== notkaramel/notkaramel.github.io/src/lib/content/schemas/publication.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "publication",
  "title": "Publication",
  "type": "object",
  "properties": {
    "title": { "type": "string" },
    "authors": {
      "type": "array",
      "items": { "type": "string" }
    },
    "type": { "type": "string" },
    "details": {
      "type": "array",
      "items": { "type": "string" }
    },
    "doi": { "type": ["string", "null"] },
    "url": { "type": ["string", "null"] }
  },
  "required": ["title", "authors", "type", "details"]
}

=== notkaramel/notkaramel.github.io/src/lib/content/publications.json
[
  {
    "type": "Conference Paper",
    "title": "Plainchant Analyser for MEI Neumes: A Tool for Understanding Chant Transmission",
    "authors": [
      "Antoine Phan",
      "Martha Thomae",
      "Elsa De Luca",
      "Francesco Orio"
    ],
    "details": [
      "Conference: Music Encoding Conference 2025",
      "Location: London, United Kingdom.",
      "Time: June 27-29, 2024"
    ],
    "url": null,
    "doi": null
  },
  {
    "type": "Confernece Paper",
    "title": "Enhancing Musicological Analysis through Digital Tools",
    "authors": ["Martha Thomae", "Antoine Phan", "Elsa De Luca"],
    "details": [
      "Conference: Digital Technologies Applied to Music Research: Methodologies, Projects and Challenges",
      "Location: Lisbon, Portugal",
      "Time: June 27-29, 2024"
    ],
    "url": null,
    "doi": null
  },
  {
    "type": "Confernece Paper",
    "title": "Music Retrieval Tools (OMR and music analysis).",
    "authors": ["Elsa De Luca", "Martha Thomae", "Antoine Phan"],
    "details": [
      "Conference: Digital Technologies Applied to Music Research: Methodologies, Projects and Challenges",
      "Location: Lisbon, Portugal",
      "Time: June 24th, 2024"
    ],
    "url": null,
    "doi": null
  }
]
